// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ViewportOffset } from "./ViewportOffset";

/**
 * Canvas viewport state.
 */
export type CanvasState = { 
/**
 * Zoom level (1.0 = 100%).
 */
zoom: number, 
/**
 * Viewport offset.
 */
viewport: ViewportOffset, };
