// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeDefinition } from "./EdgeDefinition";
import type { FlowMetadata } from "./FlowMetadata";
import type { FlowSettings } from "./FlowSettings";
import type { NodeDefinition } from "./NodeDefinition";
import type { TriggerDefinition } from "./TriggerDefinition";

/**
 * A complete flow definition from YAML.
 *
 * This is the top-level structure representing a XERV flow document.
 *
 * # Example
 *
 * ```yaml
 * name: order_processing
 * version: "1.0"
 * description: Process incoming orders with fraud detection
 *
 * triggers:
 *   - id: api_webhook
 *     type: webhook
 *     params:
 *       port: 8080
 *       path: /orders
 *
 * nodes:
 *   validate:
 *     type: std::json_parse
 *     config:
 *       strict: true
 *
 *   fraud_check:
 *     type: std::switch
 *     config:
 *       condition:
 *         type: greater_than
 *         field: risk_score
 *         value: 0.8
 *
 *   process_order:
 *     type: plugins::order_processor
 *
 *   flag_fraud:
 *     type: plugins::fraud_handler
 *
 * edges:
 *   - from: api_webhook
 *     to: validate
 *   - from: validate
 *     to: fraud_check
 *   - from: fraud_check.true
 *     to: flag_fraud
 *   - from: fraud_check.false
 *     to: process_order
 *
 * settings:
 *   max_concurrent_executions: 100
 *   execution_timeout_ms: 30000
 * ```
 */
export type FlowDefinition = { 
/**
 * Flow name (required).
 */
name: string, 
/**
 * Flow version (optional, defaults to "1.0").
 */
version: string | null, 
/**
 * Human-readable description.
 */
description: string | null, 
/**
 * Visual metadata for the web UI (optional, ignored by executor).
 */
metadata: FlowMetadata | null, 
/**
 * Triggers that start this flow.
 */
triggers: Array<TriggerDefinition>, 
/**
 * Nodes in the flow, keyed by node ID.
 */
nodes: { [key: string]: NodeDefinition }, 
/**
 * Edges connecting nodes.
 */
edges: Array<EdgeDefinition>, 
/**
 * Runtime settings.
 */
settings: FlowSettings, };
