// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime settings for a flow.
 *
 * These settings control execution behavior like concurrency limits,
 * timeouts, and circuit breaker configuration.
 */
export type FlowSettings = { 
/**
 * Maximum concurrent trace executions.
 */
max_concurrent_executions: number, 
/**
 * Execution timeout in milliseconds.
 */
execution_timeout_ms: bigint, 
/**
 * Error rate threshold for circuit breaker (0.0 to 1.0).
 */
circuit_breaker_threshold: number, 
/**
 * Window for measuring error rate in milliseconds.
 */
circuit_breaker_window_ms: bigint, 
/**
 * Maximum concurrent versions during deployment.
 */
max_concurrent_versions: number, 
/**
 * Drain timeout in milliseconds.
 */
drain_timeout_ms: bigint, 
/**
 * Grace period before hard drain in milliseconds.
 */
drain_grace_period_ms: bigint, 
/**
 * Enable debug tracing for this flow.
 */
debug: boolean, 
/**
 * Custom environment variables for this flow.
 */
env: { [key: string]: string }, };
