// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiMetadata } from "./UiMetadata";

/**
 * Visual metadata for the web UI.
 *
 * This is embedded in the YAML and ignored by the executor.
 * It stores node positions, zoom level, and other UI state.
 */
export type FlowMetadata = { 
/**
 * UI-specific metadata.
 */
ui: UiMetadata | null, };
