// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RetryConfig } from "./RetryConfig";

/**
 * A node definition from YAML.
 *
 * # Example
 *
 * ```yaml
 * nodes:
 *   fraud_check:
 *     type: std::switch
 *     description: Route based on risk score
 *     config:
 *       condition:
 *         type: greater_than
 *         field: risk_score
 *         value: 0.8
 *
 *   log_result:
 *     type: std::log
 *     config:
 *       message: "Processing complete"
 *       level: info
 *
 *   aggregate_stats:
 *     type: std::aggregate
 *     config:
 *       operation: sum
 *       field: amount
 * ```
 */
export type NodeDefinition = { 
/**
 * Node type (e.g., "std::switch", "std::merge", "plugins::fraud_model").
 */
type: string, 
/**
 * Optional description.
 */
description: string | null, 
/**
 * Whether the node is enabled.
 */
enabled: boolean, 
/**
 * Retry configuration.
 */
retry: RetryConfig | null, 
/**
 * Timeout override for this node (milliseconds).
 */
timeout_ms: bigint | null, 
/**
 * Custom labels for this node.
 */
labels: { [key: string]: string }, };
