// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Node position on canvas.
 */
export type NodePosition = { 
/**
 * X coordinate in pixels.
 */
x: number, 
/**
 * Y coordinate in pixels.
 */
y: number, };
