// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Retry configuration for a node.
 */
export type RetryConfig = { 
/**
 * Maximum number of retry attempts.
 */
max_attempts: number, 
/**
 * Initial delay between retries in milliseconds.
 */
initial_delay_ms: bigint, 
/**
 * Maximum delay between retries in milliseconds.
 */
max_delay_ms: bigint, 
/**
 * Multiplier for exponential backoff.
 */
backoff_multiplier: number, 
/**
 * Whether to add jitter to delay.
 */
jitter: boolean, };
