// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A trigger definition from YAML.
 *
 * # Example
 *
 * ```yaml
 * triggers:
 *   - id: api_webhook
 *     type: webhook
 *     params:
 *       host: "0.0.0.0"
 *       port: 8080
 *       path: "/api/orders"
 *       method: "POST"
 *
 *   - id: daily_sync
 *     type: cron
 *     params:
 *       schedule: "0 0 * * * *"  # Every hour
 *
 *   - id: file_watcher
 *     type: filesystem
 *     params:
 *       path: "/data/uploads"
 *       recursive: true
 *       events: ["create", "modify"]
 * ```
 */
export type TriggerDefinition = { 
/**
 * Unique identifier for this trigger.
 */
id: string, 
/**
 * Trigger type (webhook, cron, filesystem, queue, memory, manual).
 */
type: string, 
/**
 * Whether the trigger is enabled.
 */
enabled: boolean, 
/**
 * Optional description.
 */
description: string | null, };
