// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasState } from "./CanvasState";
import type { NodeUiState } from "./NodeUiState";

/**
 * UI-specific visual metadata.
 */
export type UiMetadata = { 
/**
 * Canvas viewport state.
 */
canvas: CanvasState, 
/**
 * Node-specific UI state, keyed by node ID.
 */
nodes: { [key: string]: NodeUiState }, };
