// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Viewport offset coordinates.
 */
export type ViewportOffset = { 
/**
 * X offset in pixels.
 */
x: number, 
/**
 * Y offset in pixels.
 */
y: number, };
